name: Build

on:
  push:
  
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: PyInstaller Action
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.10'
          spec: 'src/build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'blinker'
          options: --onefile, --name "Blinker", --windowed, 
